### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tomwilkie** [linuxerwang/goroutine-inspect#1]
```
>> original.dedupe()
panic: runtime error: index out of range

goroutine 1 [running]:
main.expr(0xc42021e000, 0x11, 0x11, 0x0)
	/Users/twilkie/Documents/src/github.com/linuxerwang/goroutine-inspect/expr.go:117 +0x14ec
main.main()
	/Users/twilkie/Documents/src/github.com/linuxerwang/goroutine-inspect/main.go:114 +0x570
```

**Comment by linuxerwang** [comment]
@tomwilkie:

The function should be dedup(), not dedupe(). I just changed the code a little so when unknown function was requested it now prints a message.

Thus I am closing this issue.
